### PR TITLE
docs: update rtd cat-vrs url

### PR DESCRIPTION
**Pull request by korikuzma**

### CODE REVIEW

**Review by DanielPuthawala — APPROVED** [review]
Thanks for catching those@

**Comment by DanielPuthawala** [comment]
@korikuzma should we be worried that the rtd check failed?

**Comment by korikuzma** [comment]
@DanielPuthawala do you have permissions to the RTD? We might have to change something there?

**Comment by korikuzma** [comment]
@DanielPuthawala it might've been something with RTD server. Going to merge.

**Pull request merged**
